const db = require('../config/db');

class Salary {
    static async create(data) {
        const { employeeNumber, grossSalary, totalDeduction, month } = data;
        // netSalary is generated by DB
        const sql = 'INSERT INTO Salary (employeeNumber, grossSalary, totalDeduction, month) VALUES (?, ?, ?, ?)';
        const [result] = await db.execute(sql, [employeeNumber, grossSalary, totalDeduction, month]);
        return result.insertId;
    }

    static async findAll() {
        const [rows] = await db.execute('SELECT * FROM Salary');
        return rows;
    }

    static async findById(id) {
        const [rows] = await db.execute('SELECT * FROM Salary WHERE salaryId = ?', [id]);
        return rows[0];
    }

    static async update(id, data) {
        const { grossSalary, totalDeduction, month } = data;
        const sql = 'UPDATE Salary SET grossSalary = ?, totalDeduction = ?, month = ? WHERE salaryId = ?';
        await db.execute(sql, [grossSalary, totalDeduction, month, id]);
    }

    static async delete(id) {
        await db.execute('DELETE FROM Salary WHERE salaryId = ?', [id]);
    }

    static async getPayrollReport(month) {
        const sql = `
        SELECT e.firstName, e.lastName, e.position, d.departmentName, s.netSalary, s.grossSalary, s.totalDeduction, s.month
        FROM Salary s
        JOIN Employee e ON s.employeeNumber = e.employeeNumber
        JOIN Department d ON e.departmentCode = d.departmentCode
        WHERE s.month = ?
    `;
        const [rows] = await db.execute(sql, [month]);
        return rows;
    }
}

module.exports = Salary;
